### ISSUE TITLE
[QUESTION] How can I open a file on a tab or a buffer?

### ISSUE THREAD

**Issue by sinetoami** [dylanaraps/fff.vim#1]
On the terminal its simple to type 'l' or 'enter' keywords. But this behavior not works inside Neovim. Or actually, I've missed something. Any advice? 

Thanks

**Comment by dylanaraps** [comment]
I don't understand. Can you elaborate?

**Comment by sinetoami** [comment]
Oh, sorry for my bad English. So, I'll try to be more clear. The `fff` file manager uses `l` and `enter` shortcuts to open a file like  `.txt`, `.rb`,  `.go` with my personal editor which is Neovim. Well, the `fff.vim` doesn't do this on my environment. I don't know if I forgot something in my  `rc` config. But I want to know how can I open files on a `buffers` or `tabs` on Neovim like Nerdtree, do you understand me? Select a file on tree, press `enter` and open that file on a buffer or tab.

I hope I have been clearer. Thanks

**Comment by dylanaraps** [comment]
Are you using the latest version of `fff`? It should work as you've described.

**Comment by sinetoami** [comment]
> Are you using the latest version of `fff`?

Yep.

My vimrc [here](https://github.com/sinetoami/dotfiles/tree/master/nvim/.nvim/nvimrc) and my [zshrc](https://github.com/sinetoami/dotfiles/tree/master/zsh)

**Comment by mgiugliano** [comment]
I might perhaps have the same question:

- when using fff within vim, pressing ENTER opens the selected file in the split window and not in a new buffer, as NERDTree..

Any suggestion on how to mimic NERDTree behaviour?

**Comment by dylanaraps** [comment]
The plugin should open files in a new buffer. What version of `fff` are you using?

**Comment by mgiugliano** [comment]
It does, after updated to the latest 'fff'. Thank you.

**Comment by sinetoami** [comment]
Yep. Now works like a charm. Thank you very much!
