### ISSUE TITLE
Selecting a file does not actually open the file

### ISSUE THREAD

**Issue by ghost** [dylanaraps/fff.vim#2]
Currently I'm using zsh and I run vim in an instance of zsh. When I run the fff file picker through vim I select a file (pressing Enter), however it doesn't actually open the file. I'm not sure of any other details I can give, just that the attempt to open a file does nothing.

**Comment by dylanaraps** [comment]
What version of `fff` are you using?

**Comment by ghost** [comment]
I'm not able  to identify it using any terminal commands that I know of, but I downloaded it from the AUR, namely the package named fff-git from the AUR.

**Comment by dylanaraps** [comment]
`fff -v`.

Also how did you install the vim plugin?

**Comment by ghost** [comment]
Interestingly I just updated my fff install using yay and the plugin seems to work. Now it's at 2.0 as I expected it to be initially. I imagine it was an earlier version when I first downloaded it from the AUR.
