### ISSUE TITLE
Disable line number

### ISSUE THREAD

**Issue by h8ed** [dylanaraps/fff.vim#5]
First off I'd like to say I love this plugin and `fff` in general, I feel it integrates with vim a tad better than `nnn`. 
Idk if this would be more of a question than an issue, but I can't figure out how to disable the line numbers when opening in vim. I like having the size around 15% on the left side, and this hogs a lot of `fff`'s real estate. I tried something like `autocmd FileType fff set nonu` but this didn't work, neither did `FileType vim` (just some silly attempt, idk if `fff` would necessarily have a designated file type. 
So, is there any way to do this? Any help is appreciated.

**Comment by h8ed** [comment]
My apologies, I looked at the latest push to the plugin, it seems it is a problem when I have `relativenumber` set. When this is set the line numbers still appear, but with it off it behaves normally

**Comment by dylanaraps** [comment]
So disabling `relativenumber` in the vim plugin solves the issue?

**Comment by h8ed** [comment]
If I disable both `relativenumber` and `number`, it works, however I don't know how to do this specifically for the `fff.vim` plugin (apologies for late reply, trying to help someone else with some git stuff lol)

**Comment by h8ed** [comment]
So basically I want `relativenumber` and `number` on the files I'm editing, but not on the `fff` split.

**Comment by dylanaraps** [comment]
I see. In the plugin code it already does `setlocal nonumber`. Are you running the latest version of the plugin?

**Comment by h8ed** [comment]
Ahh. Yes, should be latest. Installed via vim-plug by putting `Plug 'dylanaraps/fff.vim'` in my `.vimrc` and running `:PlugInstall`. The issue is that If `set relativenumber` is still on, it shows line numbers still, regardless of if `set nonumber` is on or not.

**Comment by h8ed** [comment]
perhaps `execute 'setlocal norelativenumber'` in the `autoload/fff.vim` as well?

**Comment by h8ed** [comment]
Confirmed, adding `execute 'setlocal norelativenumber'` under the `execute 'setlocal nonumber'` in `autoload/fff.vim` fixed it!

**Comment by dylanaraps** [comment]
Will push a fix! Thanks :)

**Comment by dylanaraps** [comment]
Fixed
